// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Default Suite', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('failing-test', async function() {
    await driver.get("https://agitated-lewin-f45196.netlify.app/")
    await driver.manage().window().setRect(1360, 685)
    {
      const elements = await driver.findElements(By.css(".null"))
      assert(elements.length)
    }
    await driver.findElement(By.css(".button")).click()
    await driver.close()
  })
  it('passing-test', async function() {
    await driver.get("https://agitated-lewin-f45196.netlify.app/")
    await driver.manage().window().setRect(1360, 685)
    await driver.findElement(By.css(".button")).click()
    await driver.close()
  })
})
